//this source code was auto-generated by tolua#, do not modify it
using System;
using System.Collections.Generic;
using LuaInterface;

public static class DelegateFactory
{
	public delegate Delegate DelegateValue(LuaFunction func, LuaTable self, bool flag);
	public static Dictionary<Type, DelegateValue> dict = new Dictionary<Type, DelegateValue>();

	static DelegateFactory()
	{
		Register();
	}

	[NoToLuaAttribute]
	public static void Register()
	{
		dict.Clear();
		dict.Add(typeof(System.Action), System_Action);
		dict.Add(typeof(UnityEngine.Events.UnityAction), UnityEngine_Events_UnityAction);
		dict.Add(typeof(System.Predicate<int>), System_Predicate_int);
		dict.Add(typeof(System.Action<int>), System_Action_int);
		dict.Add(typeof(System.Comparison<int>), System_Comparison_int);
		dict.Add(typeof(UnityEngine.Camera.CameraCallback), UnityEngine_Camera_CameraCallback);
		dict.Add(typeof(UnityEngine.Application.LogCallback), UnityEngine_Application_LogCallback);
		dict.Add(typeof(UnityEngine.Application.AdvertisingIdentifierCallback), UnityEngine_Application_AdvertisingIdentifierCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMReaderCallback), UnityEngine_AudioClip_PCMReaderCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMSetPositionCallback), UnityEngine_AudioClip_PCMSetPositionCallback);
		dict.Add(typeof(ToluaContainer.Container.BindingAddedHandler), ToluaContainer_Container_BindingAddedHandler);
		dict.Add(typeof(ToluaContainer.Container.BindingRemovedHandler), ToluaContainer_Container_BindingRemovedHandler);
		dict.Add(typeof(ToluaContainer.Container.Condition), ToluaContainer_Container_Condition);
		dict.Add(typeof(ToluaContainer.Container.TypeResolutionHandler), ToluaContainer_Container_TypeResolutionHandler);
		dict.Add(typeof(ToluaContainer.Container.BindingEvaluationHandler), ToluaContainer_Container_BindingEvaluationHandler);
		dict.Add(typeof(ToluaContainer.Container.BindingResolutionHandler), ToluaContainer_Container_BindingResolutionHandler);
		dict.Add(typeof(ToluaContainer.Container.InstanceInjectionHandler), ToluaContainer_Container_InstanceInjectionHandler);
		dict.Add(typeof(System.Action<UnityEngine.Object>), System_Action_UnityEngine_Object);
		dict.Add(typeof(System.Action<float>), System_Action_float);
		dict.Add(typeof(System.Action<object>), System_Action_object);
	}

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func = null)
    {
        DelegateValue create = null;

        if (!dict.TryGetValue(t, out create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));            
        }
        
        return create(func, null, false);        
    }

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func, LuaTable self)
    {
        DelegateValue create = null;

        if (!dict.TryGetValue(t, out create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));
        }

        return create(func, self, true);
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, LuaFunction func)
    {
        LuaState state = func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld.func == func)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                break;
            }
        }

        return obj;
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, Delegate dg)
    {
        LuaDelegate remove = dg.Target as LuaDelegate;

        if (remove == null)
        {
            obj = Delegate.Remove(obj, dg);
            return obj;
        }

        LuaState state = remove.func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();        

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld == remove)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                state.DelayDispose(ld.self);
                break;
            }
        }

        return obj;
    }

	class System_Action_Event : LuaDelegate
	{
		public System_Action_Event(LuaFunction func) : base(func) { }
		public System_Action_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			System.Action d = (new System_Action_Event(func)).Call;
			return d;
		}
		else
		{
			System.Action d = (new System_Action_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine.Events.UnityAction d = (new UnityEngine_Events_UnityAction_Event(func)).Call;
			return d;
		}
		else
		{
			UnityEngine.Events.UnityAction d = (new UnityEngine_Events_UnityAction_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class System_Predicate_int_Event : LuaDelegate
	{
		public System_Predicate_int_Event(LuaFunction func) : base(func) { }
		public System_Predicate_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Predicate_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Predicate<int> fn = delegate(int param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			System.Predicate<int> d = (new System_Predicate_int_Event(func)).Call;
			return d;
		}
		else
		{
			System.Predicate<int> d = (new System_Predicate_int_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class System_Action_int_Event : LuaDelegate
	{
		public System_Action_int_Event(LuaFunction func) : base(func) { }
		public System_Action_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<int> fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			System.Action<int> d = (new System_Action_int_Event(func)).Call;
			return d;
		}
		else
		{
			System.Action<int> d = (new System_Action_int_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class System_Comparison_int_Event : LuaDelegate
	{
		public System_Comparison_int_Event(LuaFunction func) : base(func) { }
		public System_Comparison_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Comparison_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Comparison<int> fn = delegate(int param0, int param1) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System.Comparison<int> d = (new System_Comparison_int_Event(func)).Call;
			return d;
		}
		else
		{
			System.Comparison<int> d = (new System_Comparison_int_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class UnityEngine_Camera_CameraCallback_Event : LuaDelegate
	{
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Camera_CameraCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Camera.CameraCallback fn = delegate(UnityEngine.Camera param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine.Camera.CameraCallback d = (new UnityEngine_Camera_CameraCallback_Event(func)).Call;
			return d;
		}
		else
		{
			UnityEngine.Camera.CameraCallback d = (new UnityEngine_Camera_CameraCallback_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class UnityEngine_Application_LogCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LogCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_LogCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_LogCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.LogCallback fn = delegate(string param0, string param1, UnityEngine.LogType param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine.Application.LogCallback d = (new UnityEngine_Application_LogCallback_Event(func)).Call;
			return d;
		}
		else
		{
			UnityEngine.Application.LogCallback d = (new UnityEngine_Application_LogCallback_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class UnityEngine_Application_AdvertisingIdentifierCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_AdvertisingIdentifierCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.AdvertisingIdentifierCallback fn = delegate(string param0, bool param1, string param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine.Application.AdvertisingIdentifierCallback d = (new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func)).Call;
			return d;
		}
		else
		{
			UnityEngine.Application.AdvertisingIdentifierCallback d = (new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class UnityEngine_AudioClip_PCMReaderCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(float[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(float[] param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMReaderCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMReaderCallback fn = delegate(float[] param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine.AudioClip.PCMReaderCallback d = (new UnityEngine_AudioClip_PCMReaderCallback_Event(func)).Call;
			return d;
		}
		else
		{
			UnityEngine.AudioClip.PCMReaderCallback d = (new UnityEngine_AudioClip_PCMReaderCallback_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class UnityEngine_AudioClip_PCMSetPositionCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMSetPositionCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMSetPositionCallback fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine.AudioClip.PCMSetPositionCallback d = (new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func)).Call;
			return d;
		}
		else
		{
			UnityEngine.AudioClip.PCMSetPositionCallback d = (new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class ToluaContainer_Container_BindingAddedHandler_Event : LuaDelegate
	{
		public ToluaContainer_Container_BindingAddedHandler_Event(LuaFunction func) : base(func) { }
		public ToluaContainer_Container_BindingAddedHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(ToluaContainer.Container.IBinder param0, ref ToluaContainer.Container.IBinding param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(ToluaContainer.Container.IBinder param0, ref ToluaContainer.Container.IBinding param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate ToluaContainer_Container_BindingAddedHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			ToluaContainer.Container.BindingAddedHandler fn = delegate(ToluaContainer.Container.IBinder param0, ref ToluaContainer.Container.IBinding param1) { };
			return fn;
		}

		if(!flag)
		{
			ToluaContainer.Container.BindingAddedHandler d = (new ToluaContainer_Container_BindingAddedHandler_Event(func)).Call;
			return d;
		}
		else
		{
			ToluaContainer.Container.BindingAddedHandler d = (new ToluaContainer_Container_BindingAddedHandler_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class ToluaContainer_Container_BindingRemovedHandler_Event : LuaDelegate
	{
		public ToluaContainer_Container_BindingRemovedHandler_Event(LuaFunction func) : base(func) { }
		public ToluaContainer_Container_BindingRemovedHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(ToluaContainer.Container.IBinder param0, System.Collections.Generic.IList<ToluaContainer.Container.IBinding> param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(ToluaContainer.Container.IBinder param0, System.Collections.Generic.IList<ToluaContainer.Container.IBinding> param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate ToluaContainer_Container_BindingRemovedHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			ToluaContainer.Container.BindingRemovedHandler fn = delegate(ToluaContainer.Container.IBinder param0, System.Collections.Generic.IList<ToluaContainer.Container.IBinding> param1) { };
			return fn;
		}

		if(!flag)
		{
			ToluaContainer.Container.BindingRemovedHandler d = (new ToluaContainer_Container_BindingRemovedHandler_Event(func)).Call;
			return d;
		}
		else
		{
			ToluaContainer.Container.BindingRemovedHandler d = (new ToluaContainer_Container_BindingRemovedHandler_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class ToluaContainer_Container_Condition_Event : LuaDelegate
	{
		public ToluaContainer_Container_Condition_Event(LuaFunction func) : base(func) { }
		public ToluaContainer_Container_Condition_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(ToluaContainer.Container.InjectionInfo param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(ToluaContainer.Container.InjectionInfo param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate ToluaContainer_Container_Condition(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			ToluaContainer.Container.Condition fn = delegate(ToluaContainer.Container.InjectionInfo param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			ToluaContainer.Container.Condition d = (new ToluaContainer_Container_Condition_Event(func)).Call;
			return d;
		}
		else
		{
			ToluaContainer.Container.Condition d = (new ToluaContainer_Container_Condition_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class ToluaContainer_Container_TypeResolutionHandler_Event : LuaDelegate
	{
		public ToluaContainer_Container_TypeResolutionHandler_Event(LuaFunction func) : base(func) { }
		public ToluaContainer_Container_TypeResolutionHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(ToluaContainer.Container.IInjector param0, System.Type param1, ToluaContainer.Container.InjectionInto param2, object param3, object param4, ref object param5)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.Push(param1);
			func.Push(param2);
			func.Push(param3);
			func.Push(param4);
			func.PushObject(param5);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(ToluaContainer.Container.IInjector param0, System.Type param1, ToluaContainer.Container.InjectionInto param2, object param3, object param4, ref object param5)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.Push(param1);
			func.Push(param2);
			func.Push(param3);
			func.Push(param4);
			func.PushObject(param5);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate ToluaContainer_Container_TypeResolutionHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			ToluaContainer.Container.TypeResolutionHandler fn = delegate(ToluaContainer.Container.IInjector param0, System.Type param1, ToluaContainer.Container.InjectionInto param2, object param3, object param4, ref object param5) { return false; };
			return fn;
		}

		if(!flag)
		{
			ToluaContainer.Container.TypeResolutionHandler d = (new ToluaContainer_Container_TypeResolutionHandler_Event(func)).Call;
			return d;
		}
		else
		{
			ToluaContainer.Container.TypeResolutionHandler d = (new ToluaContainer_Container_TypeResolutionHandler_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class ToluaContainer_Container_BindingEvaluationHandler_Event : LuaDelegate
	{
		public ToluaContainer_Container_BindingEvaluationHandler_Event(LuaFunction func) : base(func) { }
		public ToluaContainer_Container_BindingEvaluationHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public object Call(ToluaContainer.Container.IInjector param0, ref ToluaContainer.Container.IBinding param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			object ret = func.CheckVariant();
			func.EndPCall();
			return ret;
		}

		public object CallWithSelf(ToluaContainer.Container.IInjector param0, ref ToluaContainer.Container.IBinding param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			object ret = func.CheckVariant();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate ToluaContainer_Container_BindingEvaluationHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			ToluaContainer.Container.BindingEvaluationHandler fn = delegate(ToluaContainer.Container.IInjector param0, ref ToluaContainer.Container.IBinding param1) { return null; };
			return fn;
		}

		if(!flag)
		{
			ToluaContainer.Container.BindingEvaluationHandler d = (new ToluaContainer_Container_BindingEvaluationHandler_Event(func)).Call;
			return d;
		}
		else
		{
			ToluaContainer.Container.BindingEvaluationHandler d = (new ToluaContainer_Container_BindingEvaluationHandler_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class ToluaContainer_Container_BindingResolutionHandler_Event : LuaDelegate
	{
		public ToluaContainer_Container_BindingResolutionHandler_Event(LuaFunction func) : base(func) { }
		public ToluaContainer_Container_BindingResolutionHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(ToluaContainer.Container.IInjector param0, ref ToluaContainer.Container.IBinding param1, ref object param2)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PushObject(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(ToluaContainer.Container.IInjector param0, ref ToluaContainer.Container.IBinding param1, ref object param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PushObject(param1);
			func.PushObject(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate ToluaContainer_Container_BindingResolutionHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			ToluaContainer.Container.BindingResolutionHandler fn = delegate(ToluaContainer.Container.IInjector param0, ref ToluaContainer.Container.IBinding param1, ref object param2) { };
			return fn;
		}

		if(!flag)
		{
			ToluaContainer.Container.BindingResolutionHandler d = (new ToluaContainer_Container_BindingResolutionHandler_Event(func)).Call;
			return d;
		}
		else
		{
			ToluaContainer.Container.BindingResolutionHandler d = (new ToluaContainer_Container_BindingResolutionHandler_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class ToluaContainer_Container_InstanceInjectionHandler_Event : LuaDelegate
	{
		public ToluaContainer_Container_InstanceInjectionHandler_Event(LuaFunction func) : base(func) { }
		public ToluaContainer_Container_InstanceInjectionHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(ToluaContainer.Container.IInjector param0, ref object param1, ToluaContainer.Container.ReflectionInfo param2)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PushObject(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(ToluaContainer.Container.IInjector param0, ref object param1, ToluaContainer.Container.ReflectionInfo param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PushObject(param1);
			func.PushObject(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate ToluaContainer_Container_InstanceInjectionHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			ToluaContainer.Container.InstanceInjectionHandler fn = delegate(ToluaContainer.Container.IInjector param0, ref object param1, ToluaContainer.Container.ReflectionInfo param2) { };
			return fn;
		}

		if(!flag)
		{
			ToluaContainer.Container.InstanceInjectionHandler d = (new ToluaContainer_Container_InstanceInjectionHandler_Event(func)).Call;
			return d;
		}
		else
		{
			ToluaContainer.Container.InstanceInjectionHandler d = (new ToluaContainer_Container_InstanceInjectionHandler_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class System_Action_UnityEngine_Object_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Object_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_Object_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Object(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Object> fn = delegate(UnityEngine.Object param0) { };
			return fn;
		}

		if(!flag)
		{
			System.Action<UnityEngine.Object> d = (new System_Action_UnityEngine_Object_Event(func)).Call;
			return d;
		}
		else
		{
			System.Action<UnityEngine.Object> d = (new System_Action_UnityEngine_Object_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class System_Action_float_Event : LuaDelegate
	{
		public System_Action_float_Event(LuaFunction func) : base(func) { }
		public System_Action_float_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(float param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(float param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_float(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<float> fn = delegate(float param0) { };
			return fn;
		}

		if(!flag)
		{
			System.Action<float> d = (new System_Action_float_Event(func)).Call;
			return d;
		}
		else
		{
			System.Action<float> d = (new System_Action_float_Event(func, self)).CallWithSelf;
			return d;
		}
	}

	class System_Action_object_Event : LuaDelegate
	{
		public System_Action_object_Event(LuaFunction func) : base(func) { }
		public System_Action_object_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_object(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<object> fn = delegate(object param0) { };
			return fn;
		}

		if(!flag)
		{
			System.Action<object> d = (new System_Action_object_Event(func)).Call;
			return d;
		}
		else
		{
			System.Action<object> d = (new System_Action_object_Event(func, self)).CallWithSelf;
			return d;
		}
	}

}

