//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ToluaContainer_CommanderContainerAOTWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ToluaContainer.CommanderContainerAOT), typeof(System.Object));
		L.RegFunction("OnRegister", OnRegister);
		L.RegFunction("OnUnregister", OnUnregister);
		L.RegFunction("New", _CreateToluaContainer_CommanderContainerAOT);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateToluaContainer_CommanderContainerAOT(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ToluaContainer.CommanderContainerAOT obj = new ToluaContainer.CommanderContainerAOT();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ToluaContainer.CommanderContainerAOT.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRegister(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ToluaContainer.CommanderContainerAOT obj = (ToluaContainer.CommanderContainerAOT)ToLua.CheckObject(L, 1, typeof(ToluaContainer.CommanderContainerAOT));
			ToluaContainer.Container.IInjectionContainer arg0 = (ToluaContainer.Container.IInjectionContainer)ToLua.CheckObject(L, 2, typeof(ToluaContainer.Container.IInjectionContainer));
			obj.OnRegister(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUnregister(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ToluaContainer.CommanderContainerAOT obj = (ToluaContainer.CommanderContainerAOT)ToLua.CheckObject(L, 1, typeof(ToluaContainer.CommanderContainerAOT));
			ToluaContainer.Container.IInjectionContainer arg0 = (ToluaContainer.Container.IInjectionContainer)ToLua.CheckObject(L, 2, typeof(ToluaContainer.Container.IInjectionContainer));
			obj.OnUnregister(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

