//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ToluaContainer_EventContainerAOTWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ToluaContainer.EventContainerAOT), typeof(System.Object));
		L.RegFunction("OnRegister", OnRegister);
		L.RegFunction("OnUnregister", OnUnregister);
		L.RegFunction("New", _CreateToluaContainer_EventContainerAOT);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("disposable", get_disposable, set_disposable);
		L.RegVar("updateable", get_updateable, set_updateable);
		L.RegVar("eventBehaviour", get_eventBehaviour, set_eventBehaviour);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateToluaContainer_EventContainerAOT(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ToluaContainer.EventContainerAOT obj = new ToluaContainer.EventContainerAOT();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ToluaContainer.EventContainerAOT.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRegister(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ToluaContainer.EventContainerAOT obj = (ToluaContainer.EventContainerAOT)ToLua.CheckObject(L, 1, typeof(ToluaContainer.EventContainerAOT));
			ToluaContainer.Container.IInjectionContainer arg0 = (ToluaContainer.Container.IInjectionContainer)ToLua.CheckObject(L, 2, typeof(ToluaContainer.Container.IInjectionContainer));
			obj.OnRegister(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUnregister(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ToluaContainer.EventContainerAOT obj = (ToluaContainer.EventContainerAOT)ToLua.CheckObject(L, 1, typeof(ToluaContainer.EventContainerAOT));
			ToluaContainer.Container.IInjectionContainer arg0 = (ToluaContainer.Container.IInjectionContainer)ToLua.CheckObject(L, 2, typeof(ToluaContainer.Container.IInjectionContainer));
			obj.OnUnregister(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_disposable(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, ToluaContainer.EventContainerAOT.disposable);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_updateable(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, ToluaContainer.EventContainerAOT.updateable);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eventBehaviour(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ToluaContainer.EventContainerAOT.eventBehaviour);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_disposable(IntPtr L)
	{
		try
		{
			System.Collections.Generic.List<System.IDisposable> arg0 = (System.Collections.Generic.List<System.IDisposable>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<System.IDisposable>));
			ToluaContainer.EventContainerAOT.disposable = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_updateable(IntPtr L)
	{
		try
		{
			System.Collections.Generic.List<ToluaContainer.IUpdatable> arg0 = (System.Collections.Generic.List<ToluaContainer.IUpdatable>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<ToluaContainer.IUpdatable>));
			ToluaContainer.EventContainerAOT.updateable = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eventBehaviour(IntPtr L)
	{
		try
		{
			ToluaContainer.EventBehaviour arg0 = (ToluaContainer.EventBehaviour)ToLua.CheckUnityObject(L, 2, typeof(ToluaContainer.EventBehaviour));
			ToluaContainer.EventContainerAOT.eventBehaviour = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

