//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Utils_ExceptionsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Utils.Exceptions), typeof(System.Exception));
		L.RegFunction("New", _CreateUtils_Exceptions);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("PARAMETER_NUll", get_PARAMETER_NUll, null);
		L.RegVar("PARAMETERS_LENGTH_ERROR", get_PARAMETERS_LENGTH_ERROR, null);
		L.RegVar("PARAMETER_TYPE_ERROR", get_PARAMETER_TYPE_ERROR, null);
		L.RegVar("TYPE_NOT_ASSIGNABLE", get_TYPE_NOT_ASSIGNABLE, null);
		L.RegVar("NON_SPECIFIED_TYPE", get_NON_SPECIFIED_TYPE, null);
		L.RegVar("SAME_BINDING", get_SAME_BINDING, null);
		L.RegVar("BINDINGTYPE_NOT_ASSIGNABLE", get_BINDINGTYPE_NOT_ASSIGNABLE, null);
		L.RegVar("RESOURCES_LOAD_FAILURE", get_RESOURCES_LOAD_FAILURE, null);
		L.RegVar("ASSETBUNDLE_LOAD_FAILURE", get_ASSETBUNDLE_LOAD_FAILURE, null);
		L.RegVar("RESOURCE_LOAD_FAILURE", get_RESOURCE_LOAD_FAILURE, null);
		L.RegVar("NO_CONSTRUCTORS", get_NO_CONSTRUCTORS, null);
		L.RegVar("CANNOT_RESOLVE_MONOBEHAVIOUR", get_CANNOT_RESOLVE_MONOBEHAVIOUR, null);
		L.RegVar("GAMEOBJECT_IS_NULL", get_GAMEOBJECT_IS_NULL, null);
		L.RegVar("VALUE_ISNOT_PREFAB", get_VALUE_ISNOT_PREFAB, null);
		L.RegVar("SAME_OBJECT", get_SAME_OBJECT, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUtils_Exceptions(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Utils.Exceptions obj = new Utils.Exceptions();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(string)))
			{
				string arg0 = ToLua.CheckString(L, 1);
				Utils.Exceptions obj = new Utils.Exceptions(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Utils.Exceptions.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PARAMETER_NUll(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.PARAMETER_NUll);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PARAMETERS_LENGTH_ERROR(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.PARAMETERS_LENGTH_ERROR);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PARAMETER_TYPE_ERROR(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.PARAMETER_TYPE_ERROR);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TYPE_NOT_ASSIGNABLE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.TYPE_NOT_ASSIGNABLE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NON_SPECIFIED_TYPE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.NON_SPECIFIED_TYPE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SAME_BINDING(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.SAME_BINDING);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BINDINGTYPE_NOT_ASSIGNABLE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.BINDINGTYPE_NOT_ASSIGNABLE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RESOURCES_LOAD_FAILURE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.RESOURCES_LOAD_FAILURE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASSETBUNDLE_LOAD_FAILURE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.ASSETBUNDLE_LOAD_FAILURE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RESOURCE_LOAD_FAILURE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.RESOURCE_LOAD_FAILURE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NO_CONSTRUCTORS(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.NO_CONSTRUCTORS);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CANNOT_RESOLVE_MONOBEHAVIOUR(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.CANNOT_RESOLVE_MONOBEHAVIOUR);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GAMEOBJECT_IS_NULL(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.GAMEOBJECT_IS_NULL);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VALUE_ISNOT_PREFAB(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.VALUE_ISNOT_PREFAB);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SAME_OBJECT(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Utils.Exceptions.SAME_OBJECT);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

